trigger:
  - master
  - dev

jobs:
  - template: tools/azure-pipelines/test-go-versions.yml
    parameters:
      name: Debian_Linux
      vmImage: ubuntu-latest
      go:
        container: golang
        versions: [ 1.14, 1.13, 1.12 ]
        targets:
          GOARCH: [ amd64, 386 ]

  - template: tools/azure-pipelines/test-go-versions.yml
    parameters:
      name: Alpine_Linux
      vmImage: ubuntu-latest
      go:
        container: julio/azure-pipelines-golang
        versions: [ 1.14-alpine, 1.13-alpine, 1.12-alpine ]
        targets:
          GOARCH: [ amd64 ]

  - template: tools/azure-pipelines/test-go-versions.yml
    parameters:
      name: Windows
      vmImage: windows-latest
      go:
        container: golang
        versions: [ 1.14, 1.13, 1.12 ]
        targets:
          GOARCH: [ amd64, 386 ]
      testCommand: go test -v ./...

  - job: MacOS_amd64
    pool:
      vmImage: macOS-latest
    steps:
      - script: |
          go env
          clang -v
          go test -v ./...
