trigger:
  - master
  - dev

jobs:
  - template: tools/azure-pipelines/test-go-versions.yml
    parameters:
      name: Alpine_Linux
      vmImage: ubuntu-latest
      go:
        versions: [ 1.13, 1.12, 1.11 ]
        targets:
          GOARCH: [ amd64, 386 ]

  - template: tools/azure-pipelines/test-go-versions.yml
    parameters:
      name: Debian_Linux
      vmImage: ubuntu-latest
      go:
        container: sqreen/azure-pipelines-container-golang
        versions: [ 1.13-alpine, 1.12-alpine ]
        targets:
          GOARCH: [ amd64, 386 ]

  - template: tools/azure-pipelines/test-go-versions.yml
    parameters:
      name: Windows
      vmImage: windows-latest
      go:
        versions: [1.13, 1.12, 1.11]
        targets:
          GOARCH: [ amd64, 386 ]

  - job: MacOS_amd64
    pool:
      vmImage: macOS-latest
    steps:
      - script: |
          go env
          clang -v
          go test -v -x ./...

  - job: MacOS_386
    pool:
      vmImage: macOS-latest
    steps:
      - script: |
          go env
          clang -v
          env GOARCH=386 go test -v -x ./...