trigger:
  - master
  - dev

strategy:
  matrix:
    # Last two stable versions
    go1.13:
      containerImage: golang:1.13
    go1.12:
      containerImage: golang:1.12
    # Last two old stable versions
    go1.11:
      containerImage: golang:1.11
    go1.10:
      containerImage: golang:1.10

jobs:
  - job: Linux
    pool:
      vmImage: ubuntu-latest
    container: $[ variables['containerImage'] ]
    steps:
      - script: |
          go env
          gcc -v
