trigger:
  - master
  - dev



jobs:
  - template: tools/azure-pipelines/test-go-versions.yml
    parameters:
      name: Linux
      vmImage: 'ubuntu-latest'

  - template: tools/azure-pipelines/test-go-versions.yml
    parameters:
      name: Windows
      vmImage: 'windows-latest'
