parameters:
  name: ''
  vmImage: ''
  go: [ '1.13', '1.12', '1.11', '1.10' ]
  targets:
    GOARCH: [ amd64 ]

jobs:
  - job: ${{ parameters.name }}
    pool:
      vmImage: ${{ parameters.vmImage }}
    ${{ each go in parameters.go }}:
      ${{ each goarch in parameters.targets.GOARCH }}:
        container:
          image: 'golang:${{ go }}'
          env:
            GOARCH: ${{ goarch }}
        steps:
          - script: |
              go env
              gcc -v
          - ${{ if eq(goarch, 'amd64') }}:
              - script: go test -v -x ./...
              - script: go test -v -x ./... -waf.failsafe
