parameters:
  name: ''
  vmImage: ''
  go:
    container: golang
    versions: [ 1.13, 1.12, 1.11 ]
    targets:
      GOARCH: [ amd64 ]

jobs:
  - job: ${{ parameters.name }}
    pool:
      vmImage: ${{ parameters.vmImage }}
    strategy:
      matrix:
        ${{ each goVersion in parameters.go.versions }}:
          ${{ each goarch in parameters.go.targets.GOARCH }}:
            ${{ format('go{0}_{1}', goVersion, goarch) }}:
              containerImage: ${{ parameters.go.container }}:${{ goVersion }}
              GOARCH: ${{ goarch }}
    container:
      image: $(containerImage)
      env:
        GOARCH: $(GOARCH)
    steps:
      - script: go env
      - script: go test -v -x ./...
